// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpcvweumnkjwvklehuym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwY3Z3ZXVtbmtqd3ZrbGVodXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTY0NTMsImV4cCI6MjA2MzI5MjQ1M30.0mnkix6d6Uppmn80MlxJ7uGlYl2J9O1XJ8-l2-haCjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);